### PR TITLE
Support SecretKey (and SecretSubKey) packets (w/ tests)

### PR DESCRIPTION
**Pull request by abeluck**
I've added parsing of Secret[Sub]Key packets. You can parse nearly all data fields (except count and checksum).

If the packets are not protected, you can even access the raw private key material. If the packets are protected (i.e., encrypted) you cannot. In the future I might add support for decrypting the encrypted packets, but that would be quite some work as there are a bunch of cipher and hash algos.

FYI: you can export unprotected subkey packets with the following gnupg options:
`--export-options export-reset-subkey-passwd,export-minimal --export-secret-subkeys KEYID`

### CODE REVIEW

**Comment by abeluck** [comment]
In case you're interested, [Guardian Project](https://guardianproject.info) will be using this in our [OTR file converter](https://github.com/guardianproject/otrfileconverter) utility, with the end goal of keeping your OTR key in your PGP keyring as a subkey for central identity management.

**Comment by toofishes** [comment]
I took only a quick glance at this, but thanks! I'll definitely be merging the work when I get a chance to review it a bit more.

Quick note- I noticed you used a lot of end-of-line comments. I tend to be biased against these, so adjusting them to match the commenting style elsewhere would be great.

**Comment by abeluck** [comment]
Dan McGee:

> I took only a quick glance at this, but thanks! I'll definitely be merging the work when I get a chance to review it a bit more.

Great!

> Quick note- I noticed you used a lot of end-of-line comments. I tend to be biased against these, so adjusting them to match the commenting style elsewhere would be great.

Ah yea, I meant to clean those up. I tend to use EOL comments when
working through the spec just so I can remember wtf I'm doing. I'll
update the request shortly.

**Comment by abeluck** [comment]
Heya toofishes, it took awhlie, but I finally got around to cleaning up the comments.

We'd love to get this merged into an upcoming release if possible, so we can rely on pgpdump on pypi as a dependency  :)

Let me know if there are any other outstanding concerns

**Comment by toofishes** [comment]
Sure; I'll try to review and merge this weekend and get another tagged release out the door. Thanks again!

**Comment by toofishes** [comment]
Most of this is on master; I didn't do a merge of the branch so I could tweak the commits a bit to ensure Python 3 compatibility. Let me know if I missed anything.

**Comment by abeluck** [comment]
Superb, thanks so much @toofishes

**Pull request closed without merging**
