### PR TITLE
added support for PublicKeyEncryptedSessionKeyPacket

### PR DESCRIPTION
**Pull request by stef**
the code is ported from an older snapshot of pgpdump, ymmv.

### CODE REVIEW

**Comment by stef** [comment]
for reference: https://tools.ietf.org/html/rfc4880#section-5.1

**Comment by toofishes** [comment]
This is great, thanks. Any change you have a packet of this type I can include so either you or I can write a test case for this new parser? If it isn't something terribly private, the easiest thing to include might be the base64-encoded equivalent of the entire packet or something.

**Comment by stef** [comment]
below an example, can be generated easily with "gpg --throw-keyids--encrypt --armor -r <keyid>"

-----BEGIN PGP MESSAGE-----
Version: GnuPG v1.4.12 (GNU/Linux)

hQIMAwAAAAAAAAAAARAAk8cZSBxr9lASnkeRsLw6JEKCAxuNC+LbTS9lzcJQ23kz
Hapvq7m4hMtXJXa3PmKjSCwAsYGvUysTfIWbHazvtvvOEAtIfgUAstgo/TmkyHY0
aLkmemRBhpkauE4dqSZ98lRC9bFcwcB2alb8XYSoBdvpjHBA9cpSNwUlXT8kqwnv
gpIJYRnYxKF+Mg5000zSN4H2aPfQ3h0ZHF3QHMTxZwyzoZsmURNwaIERUoxbtwir
QW+N/m/I7LV0lTdE1sMSCE9JbRLiXrki8BRHk+RW7iIML38ofGaXpLD92GYdg4D0
XKamDL8SisCfcA8Ukp+7aVi2qEjJ4lOGvItXX1EejUa5Ulc3c78svg4RYAW8K+Sq
qgb/14PP2VfeNlu+A7hO7ufzGM/CLVGf/f1WzAhzNnwa3sLDHQdJV8Mvutyomx27
0ZX/N8xBFjR32CjgdagvoQxPsGDI8SiU19ggBH4sbzjElnOWSAfq2A6AjACKfCMv
RlktudM1wvblQAGbqe5mpbi3ZYoiYZD911+Lnez26uaonLmRTRammXDk2Uw/Lami
adDFBzqhZHIo7oJN2b2ew/Y1b2uDGQRB8QjZmWUb2hUAn/HqTKqTsKMvj7vPTFGI
6jqX7sT8LnCgWE1jJ3tx7EvO/Jo7wC9au9P+RIohMyZm8ZD53UqZLh1CFncgkjvS
6QF/iA0VUQrDzYRFGT56AnTZEg1gQKj/4qJFsATNKPKmU1OXhVH7wgKOQhepCvzn
6gtUQhCaNFClGxqg487Xwl16sS2Rx+/7WBfF3e2VXnOVfz3lUhYO2SF0yraSJ+CP
xEjl33fkgpRRVdYlrUyJ59070srZoimUhSlRF3ngeCBxUFcGZMyrBw6czA+rYJJ8
4Iy4fLhYrTj1B0rzTkuSwXaX2H0qdpctypIzFv5k55Ozuc5g6BvtsSjt509g3lU4
6cRYcfdIDNpUA3vjDfU9VJzx2bHbRgyM2XNxPL+oVEm+vI/dCYvpsu7ZSbMPGlv6
dnD/A+JYVIWp8CMNF5Iozz89xgRCPBGQBf3GVGLkQLrF2j7rywVRWOrihV2C+S8g
tXe3N7VGca+USi4Nzro2PVxGLCrlXqCGnhn6dFo8AIWUwkrMgVd4luteZo3mhkt7
dwhLXvveHSelw/i6y5EK/Zyp3D4JuPmE1O9Qn2hXc3yLq93MiHBxaIsQar/a4aJl
S5OPVVkyIoX0yO8Xv1KnHh9QRNB++IYyttxr5ITrQzYETUerjAPOHSGwHDnnJjZh
pswmBxn92MMgPAd2XGnvVuohLGMNd+lCTZGp4SbF/zwK5sal4zeJ7SoESK0Tzjac
METFKcF2BGJzvHA+aYtLCHHD7aiAqZjJQfY8l7GunaPwwDrpZN6LKE77dhGm+I8V
0nGTu6ut66tQSR/NSVW+Eq8vW70H9izbhVWZi8fU6NoJg6fz2qbZ13ciA2lGk/Y7
VOlmRex6JyaUdqLmpZ8dXuB9r+8zREpLpc1u3wBwqbOyz5MEk23Vl2T/Sun8Ejes
auuJQVrbcvjzpvr33SpEKsSCK2iMkeuc8cl3KRI86PNTlpZSPKlrqK2FfGeLPwzd
31H660H+1eMjK7tqMAOqio77MNmbq9aa9Xw/ocgpL6hkERiiiPo2u0CUhrhVojb1
bT1zgF2z6FCMb3XpqEt+tk/Je21RbtuROXWvXRL4xcrTc5ea1NNeuc3ApOyP
=ZtdK
-----END PGP MESSAGE-----

**Comment by toofishes** [comment]
Pushed and added test cases with only minor tweaks, thanks!

**Pull request closed without merging**
